name: Playwright Python Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright pytest pytest-html
          playwright install --with-deps

      - name: Run Playwright tests
        run: |
          pytest -s tests/ --html=reports/report.html --self-contained-html

      - name: Upload HTML report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: pytest-html-report
          path: reports/report.html
